name: Publish Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2
        with:
           configuration: "config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}

  discord:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs:
      - release
    if: ${{ success() }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.CR_PAT }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: 'DockServerRelease-Bot'
          avatar-url: 'https://octodex.github.com/images/Terracottocat_Single.png'
          title: 'DockServerRelease-Bot: {{STATUS}}'
          description: 'DockServerRelease-Bot create new Release for ${{ github.repository }}'
          include-details: 'true'
          color-success: '#4287f5'
          color-failure: 'eb4034'
          color-cancelled: '0x42daf5'
